name: Build and release 🚀
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle
        run: ./gradlew bundle --continue
      - name: Sign app
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/fullRelease/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload app to wolfia
        uses: wolfia-app/wolfia-deploy@v0.0.10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          wolfia-api-key-id: ${{ vars.WOLFIA_API_KEY_ID }}
          wolfia-api-key-secret: ${{ secrets.WOLFIA_API_KEY_SECRET }}
          app-path: ${{steps.sign_app.outputs.signedReleaseFile}});
